version: '3'

services:
  airflow:
    image: apache/airflow:2.7.3-python3.10
    container_name: mlops_airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags/data_pipeline_dag.py:/opt/airflow/dags/data_pipeline_dag.py
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: airflow standalone