global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook-site-notifications'

receivers:
- name: 'webhook-site-notifications'
  webhook_configs:
  - url: 'https://webhook.site/431b2c48-c3d5-42d0-92cc-8838af470f3f'
    send_resolved: true