apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: course-api-ingress
spec:
  rules:
    - host: course-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: course-api-service
                port:
                  number: 80
